-- HR 초기 상태 lock -> unlock / pw 변경
--ALTER USER HR IDENTIFIED BY 1234 ACCOUNT UNLOCK;
-- SCOTT : 차후 적용 예정

-- SAMPLE
CREATE USER SAMPLE IDENTIFIED BY 1234;
GRANT CONNECT, RESOURCE TO SAMPLE;

GRANT CREATE VIEW TO SAMPLE;

SELECT * FROM SAMPLE.STUDENT

-- 관리자의 경우 언제나 해당 


-- SAMPLE 이 HR의 EMPLOYEES의 셀렉트 할 수 있는 권한 부여
GRANT SELECT 
ON HR.EMPLOYEES
TO SAMPLE;


-- SAMPLE 이 HR의 EMPLOYEES의 셀렉트 할 수 있는 권한 철회
REVOKE SELECT 
ON HR.EMPLOYEES
FROM SAMPLE;

GRANT CREATE PUBLIC SYNONYM TO SAMPLE;      

GRANT DBA TO SAMPLE;

CREATE PUBLIC SYNONYM STU FOR SAMPLE.STUDENT;
DROP PUBLIC SYNONYM STU;