-- 사번, 이름, 부서번호, 부서이름 조회

SELECT FIRST_NAME, LAST_NAME, EMPLOYEE_ID, E.DEPARTMENT_ID, D.DEPARTMENT_NAME 
FROM EMPLOYEES e, DEPARTMENTS d 
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- 선생님 코드
SELECT EMPLOYEE_ID, FIRST_NAME || ' ' || LAST_NAME NAME, DEPARTMENT_ID, DEPARTMENT_NAME 
FROM EMPLOYEES e
JOIN DEPARTMENTS d USING(DEPARTMENT_ID)

SELECT * FROM DEPARTMENTS d;
SELECT * FROM LOCATIONS l ;

-- 교수별 급여 등급을 조회한다, 대상테이블을 PROFESSOR, SALGRADE와 같은 테이블을 활용한다. 



--사번, 성, 상사의 사번, 상사의 성

SELECT E.EMPLOYEE_ID, E.LAST_NAME, E.MANAGER_ID, E.LAST_NAME
FROM EMPLOYEES e 
LEFT JOIN EMPLOYEES e2  ON E.MANAGER_ID = E2.EMPLOYEE_ID 
ORDER BY 1;

-- JOIN의 조건은 결국 AND 느낌임

