SELECT * FROM TAB;



SELECT * FROM STUDENT s ;
SELECT * FROM DEPARTMENT d ;
SELECT * FROM PROFESSOR p ;

SELECT count(s.DEPTNO), d.DNAME 
FROM STUDENT s, DEPARTMENT d 
WHERE s.DEPTNO = d.DEPTNO 
GROUP BY s.DEPTNO , d.DNAME 



SELECT DISTINCT GRADE || "-" || DEPTNO FROM STUDENT s 

